# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: tiipiik.catalog::lang.categories.reorder

# Attribute name
nameFrom: title

# Model Class name
modelClass: Tiipiik\Catalog\Models\Category

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar