# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: tiipiik.catalog::lang.products.reorder

# Attribute name
nameFrom: title

# Model Class name
modelClass: Tiipiik\Catalog\Models\Product

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar