# ===================================
#  Relation Behavior Config
# ===================================

customfields:
    label: tiipiik.catalog::lang.products.custom_fields_relation # Could not translate in lang.php because it's not parsed in custom field creation form
    list: $/tiipiik/catalog/models/customvalue/columns.yaml
    form: $/tiipiik/catalog/models/customvalue/fields.yaml
    emptyMessage: tiipiik.catalog::lang.products.custom_fields_empty
    toolbar: 
        buttons: false
    view:
        showCheckboxes: false

# ===================================
#  Relation Behavior Config
# ===================================

properties:
    label: tiipiik.catalog::lang.products.properties_relation
    emptyMessage: tiipiik.catalog::lang.products.properties_empty
    scope: isUsed
    view:
        list: $/tiipiik/catalog/models/property/pivot_columns.yaml
        toolbarButtons: add|remove

    manage:
        list: $/tiipiik/catalog/models/property/columns.yaml

    pivot:
        form:
            fields:
                pivot[value]:
                    label: tiipiik.catalog::lang.properties.value
                    type: text

        recordsPerPage: 50